services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file: ./api/.env
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"

  dashboard:
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    command: ["npm", "start"]