{{- if .Values.secrets.create -}}
apiVersion: v1
kind: Secret
metadata:
  name: findash-secrets
  labels:
    app: findash
type: Opaque
data:
  auth0-domain: {{ .Values.secrets.findashSecrets.auth0-domain | b64enc | quote }}
  auth0-client-id: {{ .Values.secrets.findashSecrets.auth0-client-id | b64enc | quote }}
  datadog-api-key: {{ .Values.secrets.findashSecrets.datadog-api-key | b64enc | quote }}
  datadog-app-key: {{ .Values.secrets.findashSecrets.datadog-app-key | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: findash-postgresql
  labels:
    app: findash
type: Opaque
data:
  postgres-url: {{ .Values.secrets.postgresql.postgres-url | b64enc | quote }}
{{- end }} 