name: Backend Tests and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    paths:
      - 'api/**'
      - '.github/workflows/test.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
      checks: write
      id-token: write
      security-events: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v1
      id: uv

    - name: Install backend dependencies with UV
      working-directory: ./api
      run: |
        uv pip install --system ".[dev]" .

    - name: Run black
      working-directory: ./api
      run: |
        black --check .

    - name: Run flake8
      working-directory: ./api
      run: |
        flake8

    - name: Run backend tests with coverage
      working-directory: ./api
      run: |
        pytest --cov=app --cov-report=xml:coverage.xml

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}