name: Build and Push to GitHub Packages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io
  # github.repository automatically references your repository in the format owner/repo
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the GITHUB_TOKEN for this job
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Dashboard
        uses: docker/build-push-action@v4
        with:
          context: ./dashboard
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/dashboard:latest

      - name: Build and push API
        uses: docker/build-push-action@v4
        with:
          context: ./api
          push: true
          tags: ${{ env.REGISTRY }}/${{ github.repository }}/api:latest 