name: Run Tests and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v1
      id: uv
      with:
        add-to-path: true

    - name: Install dependencies with UV
      working-directory: ./api
      run: |
        uv pip install --system ".[dev]" .

    - name: Run black
      working-directory: ./api
      run: |
        black --check .

    - name: Run flake8
      working-directory: ./api
      run: |
        flake8

    - name: Run tests
      working-directory: ./api
      run: |
        pytest --ignore-glob="*e2e.py"