name: Run Tests and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        curl -sSL https://github.com/astral-sh/uv/releases/download/v0.5.4/uv-0.5.4-linux-amd64.tar.gz | tar -xz -C /usr/local/bin

    - name: Move to API directory
      run: cd api

    - name: Install dependencies with UV
      run: uv sync --frozen

    - name: Run black
      run: uv run black --check .

    - name: Run flake8
      run: uv run flake8

    - name: Run tests
      run: uv run pytest