
name: Run Tests and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install uv
      uses: astral-sh/setup-uv@v1

    - name: Install dependencies with UV
      working-directory: ./api
      run: |
        uv pip install --system .

    - name: Run black
      working-directory: ./api
      run: |
        $HOME/.cargo/bin/uv pip install --system black
        black --check .

    - name: Run flake8
      working-directory: ./api
      run: |
        $HOME/.cargo/bin/uv pip install --system flake8
        flake8

    - name: Run tests
      working-directory: ./api
      run: |
        $HOME/.cargo/bin/uv pip install --system pytest
        pytest
