
name: Run Tests and Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh

    - name: Install dependencies with UV
      working-directory: ./api
      run: |
        uv --system pip install -r pyproject.toml

    - name: Run black
      working-directory: ./api
      run: uv run  --system black --check . 

    - name: Run flake8
      working-directory: ./api
      run: uv run --system flake8

    - name: Run tests
      working-directory: ./api
      run: uv run --system pytest
